# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies: [flake8-docstrings]
  - repo: https://github.com/pycqa/bandit
    rev: 1.6.2
    hooks:
      - id: bandit
        args: ['-iii', '-ll']
